### ISSUE TITLE
Does not focus on the item

### ISSUE THREAD

**Issue by DevDokus** [Tizzi/fivem-Character-Creator#7]
The looks and feelings of this menu is very nice. 
Only it does not focus zoom on the item you are changing,
so if you are doing something like your shoes, it is quit hard to 
get them in view.

**Comment by LapinO-dev** [comment]
Do you find an tips for that ^^ ?

**Comment by DevDokus** [comment]
Like panning the view to the item your changing?  haha
But best tip i can give you is to use the Cubes framework instead
of using ESX what is as instable as anything. 

After we left ESX we have so much more stability
